[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "move-fcg-analyzer"
version = "1.0.0"
description = "Move 项目索引与函数调用图分析的轻量 Python 库"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "tree-sitter>=0.20.0",
]

[project.scripts]
move-fcg-analyzer = "move_fcg_analyzer.cli:main"
